### PR TITLE
Proposed changes for mzml 1.1.1

### LINKED ISSUE #8: `xs:ID` type of `id` attribute of `RunType` makes many mzml files starting with digits as file or sample name invalid.
We're currently implementing a validator tool in Galaxy that simply takes an mzml file and uses the XSD schema to validate files using pyxml or xmllinter and we found that the `<run> ... </run>` field has an id attribute which has to be an `xs:ID` type, meaning it can't start with a number. But proteowizard seems to be filling this field with the sample name, which can contain a number at the start (and often does, like the position, order in the study, timestamp etc.), meaning that many mzml files which start with a number are technically invalid.

I personally don't see a reason why the `id` of the `RunType` can't be a `xs:string` - was there a specific reason for the decision?

I'd therefore like to propose to change the `id` attribute of the `RunType` from `xs:ID` to `xs:string`.

If you agree with the change I can open up a PR with the requested changes to the XSD file. Is there anything else that has to be adapted to make this change?

### PR DESCRIPTION
**Pull request by hechth**
Closes #8 

Changed the type of the id attribute to be a string allowing everything but whitespace characters and replacing everything that is a whitespace with a single space (which is invalid).

### CODE REVIEW

**Review by mobiusklein — APPROVED** [review]

**Comment by edeutsch** [comment]
Since it is challenging to see the differences because these are new files, for the record, the changes are:
1) Bump in version numbers
2) Change from Windows line-endings to Unix line-endings. Will this cause a problem for anyone???
3) Change:
```
  <xs:complexType name="RunType">
        <xs:attribute name="id" type="xs:ID" use="required">
          <xs:annotation>
            <xs:documentation>A unique identifier for this run.</xs:documentation>
```
to:
```
        <xs:attribute name="id" use="required" type="xs:string">
          <xs:annotation>
            <xs:documentation>A unique string identifier for this run.</xs:documentation>
```

The primary reason for this is that many converters simply use the filename as the id, but xs:ID limits the permitted characters and as a result many mzML files in the wild are invalid because the encoded run id uses disallowed characters.

Since there seems little reason to insist that run id conforms to xs:ID, we will just change it to xs:string.

Does this seem sensible to @chambm and others?

**Review by edeutsch — APPROVED** [review]
Seems good to me. Are we all fine with the change in line endings from Windows to Unix?

**Comment by mobiusklein** [comment]
An XML parser should be affected by changing the line ending.

All seems well.

**Comment by hechth** [comment]
@edeutsch @mobiusklein Thanks for having another look at it!

**Comment by chambm** [comment]
You're talking about the line endings in the schema itself changing? I can't imagine that causing a problem for any validating parser, but note that pwiz doesn't use one (it doesn't validate against the schema). Pwiz actually does encode the XML ID and IDREFs properly (escaping the starting character if it's not alphabetical or '_') but I can certainly believe a lot of other file writers don't.

Note that an empty string is not a valid ID, but is a valid `xs:string`. It probably needs a constraint added to disallow that.

**Comment by mobiusklein** [comment]
There's no reason to allow it to be empty, as that'd violate the _other_ semantics of `xsd:ID`. I've added the necessary XSD directive.

**Pull request merged**
